<?php
// Allow requests from any origin (CORS fix)
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json");

// Check if 'number' is provided
if (!isset($_GET['number'])) {
    http_response_code(400);
            echo json_encode(["error" => "No number provided."]);
                        exit;
                                    }

                                                $number = $_GET['number'];

                                                            // Validate: must be 11 digits, start with '01'
                                                                        if (!preg_match('/^01\d{9}$/', $number)) {
                                                                                        http_response_code(400);
                                                                                                            echo json_encode(["error" => "Invalid number format. Must be 11 digits starting with 01."]);
                                                                                                                                    exit;
                                                                                                                                                            }

                                                                                                                                                                                    $url = "https://call-bombers.vercel.app/send-call";
                                                                                                                                                                                                            $key = "DH Alamin Hasan";
                                                                                                                                                                                                                                    $repeat = 5;

                                                                                                                                                                                                                                                            $apiUrl = "$url?key=" . urlencode($key) . "&number=$number&repeat=$repeat";

                                                                                                                                                                                                                                                                                    $ch = curl_init();
                                                                                                                                                                                                                                                                                                            curl_setopt($ch, CURLOPT_URL, $apiUrl);
                                                                                                                                                                                                                                                                                                                                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                                                                                                                                                                                                                                                                                                                                                            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                                                                                                                                                                                                                                                                                                                                                                                        "User-Agent: Mozilla/5.0",
                                                                                                                                                                                                                                                                                                                                                                                                                        "Accept: application/json"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $response = curl_exec($ch);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (curl_errno($ch)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            http_response_code(500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo json_encode(["error" => "Curl error: " . curl_error($ch)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo $response;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                curl_close($ch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>