<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    <title>Call Bomber By Tausif Zaman</title>
      <style>
          body {
                margin: 0;
                      font-family: 'Segoe UI', sans-serif;
                            background: linear-gradient(135deg, #ff9a9e, #fad0c4);
                                  display: flex;
                                        flex-direction: column;
                                              align-items: center;
                                                    justify-content: center;
                                                          height: 100vh;
                                                                color: #333;
                                                                    }

                                                                        h1 {
                                                                              font-size: 2.5em;
                                                                                    animation: fadeIn 2s ease;
                                                                                        }

                                                                                            small {
                                                                                                  font-size: 0.9em;
                                                                                                        margin-top: -10px;
                                                                                                              color: #444;
                                                                                                                  }

                                                                                                                      .container {
                                                                                                                            background: #fff;
                                                                                                                                  padding: 2em;
                                                                                                                                        border-radius: 40px;
                                                                                                                                              box-shadow: 0 15px 25px rgba(0,0,0,0.2);
                                                                                                                                                    text-align: center;
                                                                                                                                                          animation: popIn 1s ease;
                                                                                                                                                              }

                                                                                                                                                                  input[type="text"] {
                                                                                                                                                                        padding: 0.7em;
                                                                                                                                                                              width: 250px;
                                                                                                                                                                                    border: 2px solid #ccc;
                                                                                                                                                                                          border-radius: 10px;
                                                                                                                                                                                                font-size: 1em;
                                                                                                                                                                                                    }

                                                                                                                                                                                                        button {
                                                                                                                                                                                                              margin-top: 1em;
                                                                                                                                                                                                                    padding: 0.7em 2em;
                                                                                                                                                                                                                          background: #ff416c;
                                                                                                                                                                                                                                color: white;
                                                                                                                                                                                                                                      font-size: 1em;
                                                                                                                                                                                                                                            border: none;
                                                                                                                                                                                                                                                  border-radius: 12px;
                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                              animation: pulse 2s infinite;
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                      #message {
                                                                                                                                                                                                                                                                            margin-top: 1em;
                                                                                                                                                                                                                                                                                  font-weight: bold;
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                          .instagram-btn {
                                                                                                                                                                                                                                                                                                margin-top: 2em;
                                                                                                                                                                                                                                                                                                      padding: 1em 2em;
                                                                                                                                                                                                                                                                                                            background: linear-gradient(45deg, #feda75, #d62976, #962fbf, #4f5bd5);
                                                                                                                                                                                                                                                                                                                  color: white;
                                                                                                                                                                                                                                                                                                                        text-decoration: none;
                                                                                                                                                                                                                                                                                                                              font-size: 1.2em;
                                                                                                                                                                                                                                                                                                                                    border-radius: 30px;
                                                                                                                                                                                                                                                                                                                                          animation: bounce 2s infinite;
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                  @keyframes popIn {
                                                                                                                                                                                                                                                                                                                                                        from { transform: scale(0.8); opacity: 0; }
                                                                                                                                                                                                                                                                                                                                                              to { transform: scale(1); opacity: 1; }
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                      @keyframes pulse {
                                                                                                                                                                                                                                                                                                                                                                            0%, 100% { box-shadow: 0 0 0 0 rgba(255,65,108, 0.6); }
                                                                                                                                                                                                                                                                                                                                                                                  50% { box-shadow: 0 0 0 15px rgba(255,65,108, 0); }
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                          @keyframes bounce {
                                                                                                                                                                                                                                                                                                                                                                                                0%, 100% { transform: translateY(0); }
                                                                                                                                                                                                                                                                                                                                                                                                      50% { transform: translateY(-5px); }
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              @keyframes fadeIn {
                                                                                                                                                                                                                                                                                                                                                                                                                    from { opacity: 0; transform: translateY(-20px); }
                                                                                                                                                                                                                                                                                                                                                                                                                          to { opacity: 1; transform: translateY(0); }
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                <body>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1>Call Bomber 💣</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <small>By Tausif Zaman</small>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" id="number" placeholder="Enter 01XXXXXXXXX">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onclick="sendCall()">Send</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div id="message"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a class="instagram-btn" href="https://instagram.com/_tausif_zaman" target="_blank">Follow Me on Instagram</a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              function sendCall() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const number = document.getElementById('number').value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const messageDiv = document.getElementById('message');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const userAgent = navigator.userAgent;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Validate number format
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!/^01\d{9}$/.test(number)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messageDiv.textContent = "Invalid number! Must be 11 digits and start with 01.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              messageDiv.style.color = "red";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Block specific number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (number === "01612219759") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      messageDiv.textContent = "Fuck you motherchod 🤧";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messageDiv.style.color = "red";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Send to logger (optional)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fetch('logger.php', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: `number=${number}&ua=${encodeURIComponent(userAgent)}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Call the API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messageDiv.textContent = "Sending call...";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fetch(`https://tausifzaman.free.nf/CallBomber/call.php?number=${number}`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .then(res => res.json()) // assuming your PHP returns JSON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (data.error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              messageDiv.textContent = "Error: " + data.error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messageDiv.style.color = "red";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          messageDiv.textContent = "Call sent successfully!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messageDiv.style.color = "green";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .catch(err => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messageDiv.textContent = "Failed to send call.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messageDiv.style.color = "red";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>